export const ROLE_CODE = {
  ADMIN: 'ADMIN'
};

export const STATUS_CODE = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};
export const USER_STATUSES = { 0: 'Khoá', 1: 'Hoạt động' };

export const NATIVE_ACTION = {
  GO_BACK: 'GO_BACK',
  OPEN_NEW_WEBVIEW: 'OPEN_NEW_WEBVIEW',
  OPEN_PDF_VIEWER: 'OPEN_PDF_VIEWER',
  CHOOSE_PHOTO: 'CHOOSE_PHOTO',
  GET_CONTACT: 'GET_CONTACT',
  OPEN_MINIAPP: 'OPEN_MINIAPP',
  OPEN_BROWSER: 'OPEN_BROWSER',
  SHARE_LINK: 'SHARE_LINK',
  PAYMENT_HUB_TRANSACTION: 'PAYMENT_HUB_TRANSACTION',
  PAYMENT_HUB_AUTO_DEBIT: 'PAYMENT_HUB_AUTO_DEBIT',
  CLOSE_WEBVIEW: 'CLOSE_WEBVIEW',
  LOADING_DONE: 'LOADING_DONE',
  TEL: 'TEL',
  EMAIL: 'EMAIL',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
  GET_LOCATION: 'GET_LOCATION',
  REQUEST_CAMERA: 'REQUEST_CAMERA',
  OPEN_SMS: 'OPEN_SMS'
};

export const HOME_BLOCK_TYPE = {
  HOME: 'HOME',
  NEW: 'NEW',
  BANNER: 'BANNER',
  COMING: 'COMING',
  SEEN: 'SEEN',
  CLOSED_BETA: 'CLOSED_BETA'
};

export const TAG_POSITION = {
  TOP: 'TOP',
  BOTTOM: 'BOTTOM'
};

export const TAG_OPTION = {
  OPTION_1: 'OPTION_1',
  OPTION_2: 'OPTION_2',
  OPTION_3: 'OPTION_3',
  OPTION_4: 'OPTION_4',
  OPTION_5: 'OPTION_5'
};
